# Generated by Django 4.2.7 on 2026-08-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
        ('store', '0003_remove_variation_color_remove_variation_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_varation', to='product.product'),
        ),
    ]
