# Generated by Django 4.2.7 on 2026-08-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
        ('store', '0004_remove_variation_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='size',
        ),
        migrations.AddField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], default='color', max_length=100),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.product'),
        ),
    ]
