# Generated by Django 4.2.7 on 2026-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_price',
            field=models.IntegerField(default=0, help_text='Original price before discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Current selling / discounted price'),
        ),
    ]
