# Generated by Django 4.2.7 on 2026-08-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_variation_value_remove_variation_var_category_and_more'),
        ('cart', '0010_remove_cartitem_is_active_cartitem_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
