# Generated by Django 4.2.7 on 2026-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cartitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Promo code text (e.g. NEPCART10)', max_length=50, unique=True)),
                ('discount_percent', models.IntegerField(help_text='Percentage discount (e.g. 10 for 10% OFF)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
