# Generated by Django 4.2.7 on 2026-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Deliverred', 'Delivered'), ('Cancaled', 'Cancaled'), ('Ongoing', 'Ongoing')], default='Paid', max_length=10),
        ),
    ]
